languageCode = 'en-us'
title = 'sudoers blog'
pagination.pagerSize = 5

[markup.goldmark.renderer]
  unsafe = true

[params]
  contentTypeName = "posts"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "Terminal"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "sudoers"
      logoHomeLink = "https://tharun-kumar-a-01.github.io/sudoers"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog/"
