languageCode = 'en-us'
title = 'sudoers blog'
pagination.pagerSize = 5

[markup.goldmark.renderer]
  unsafe = true

[params]
  contentTypeName = "posts"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "sudoers"
    subtitle = "A Group of Hacktivists and Open Source Enthusiasts"
    keywords = "sudoers, sudo-ers, community, tech community"
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "sudoers"
      logoHomeLink = "https://sudo-ers.github.io/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "blog"
        url = "/blog/"
      [[languages.en.menu.main]]
        identifier = "events"
        name = "events"
        url = "/events/"
