languageCode = 'en-us'
title = 'sudoers blog'
pagination.pagerSize = 5

[markup]
    [markup.goldmark]
        [markup.goldmark.extensions]
            typographer = false
        [markup.goldmark.renderer]
            unsafe = true

[params]
  contentTypeName = "posts"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "sudoers"
    subtitle = "A Group of Hacktivists and Open Source Enthusiasts"
    keywords = "sudoers, sudo-ers, community, tech community"
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "sudoers"
      logoHomeLink = "https://sudo-ers.github.io/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "rss"
        name = "rss"
        url = "/blog/index.xml"
      [[languages.en.menu.main]]
        identifier = "back"
        name = ".."
        url = "../"
[outputs]
  home = ['html']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']
